name = "ComputableDAGs"
uuid = "62933717-1c9d-4a3f-b06f-7ab7f17ca32d"
authors = ["Anton Reinhard <a.reinhard@hzdr.de>", "Uwe Hernandez Acosta <u.hernandez@hzdr.de>"]
version = "0.1.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
NumaAllocators = "21436f30-1b4a-4f08-87af-e26101bb5379"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[extensions]
AMDGPUExt = "AMDGPU"
CUDAExt = "CUDA"
oneAPIExt = "oneAPI"

[compat]
AMDGPU = "1"
CUDA = "5"
DataStructures = "0.18"
NumaAllocators = "0.2"
RuntimeGeneratedFunctions = "0.5"
StaticArrays = "1"
julia = "1.10"
oneAPI = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test"]
